import Anthropic from "@anthropic-ai/sdk";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import { z } from "zod";

import type { GeneratedSiteDraft, Locale, SiteGenerationInput } from "@/core/types";
import { logger } from "@/lib/logger";
import { categoryLabel, placeName } from "@/site/i18n";
import { pickTemplate, TEMPLATES } from "@/site/templates";

import { MockSiteGenerator } from "./mock";
import type { SiteGenerator } from "./types";

/**
 * Claude-backed generator.
 *
 * The model writes copy and picks a template. It does not write markup: layout,
 * spacing, and type come from `src/site/templates`, so every site is correct by
 * construction and two businesses in the same category still look different.
 *
 * The hard rule is that these pages go live for real businesses under their own
 * name. The model may not assert anything the input doesn't support — no
 * invented services, prices, founding dates, or awards. Anything it wants to
 * say beyond the data goes in `unverifiedClaims` for a human to confirm, and a
 * lead with unverified claims cannot be approved without review.
 */

const localizedSchema = z.object({
  el: z.string().describe("Greek text"),
  en: z.string().describe("English text"),
});

const draftSchema = z.object({
  tagline: localizedSchema.describe("2-4 words: what this business is. Shown above the name."),
  heroHeading: localizedSchema.describe("The business name, or a very short phrase built from it."),
  heroSubheading: localizedSchema.describe("One sentence. What they do and where. No adjectives that aren't supported by the data."),
  statement: localizedSchema.describe("8-16 words, two lines. A plain, warm statement of what visiting is like. No marketing superlatives."),
  about: localizedSchema.describe("2-3 sentences drawn strictly from the supplied facts."),
  services: z
    .array(
      z.object({
        name: localizedSchema,
        description: localizedSchema.optional(),
      }),
    )
    .max(6)
    .describe("Only services implied with certainty by the business category. Empty array if unsure."),
  template: z.enum(["editorial", "taverna", "clinic", "workshop"]).describe("Visual template that best suits this business."),
  unverifiedClaims: z
    .array(z.string())
    .describe("Anything you asserted that the input data does not directly support. Empty if nothing."),
});

const SYSTEM = `You write copy for one-page websites for small businesses in Cyprus.

These pages go live under the business's own name, at their own address, with their real phone number. A visitor will read what you write and act on it.

Absolute rules:
- Never state a fact the input does not contain. No invented services, prices, opening hours, years in business, family history, awards, specialities, or claims about quality.
- If you are not certain a business offers something, leave it out. An accurate short page beats a rich invented one.
- Anything you write that goes beyond the supplied data must be listed in unverifiedClaims, verbatim.
- Do not use marketing cliches: no "elevate", "seamless", "unleash", "your trusted partner", "we pride ourselves".
- Do not invent testimonials, ratings, or customer counts.

Language:
- Write natural Greek and natural English. The Greek is the primary version — write it first and write it well, not as a translation of the English.
- Cyprus Greek usage, standard modern Greek spelling.
- Never translate the business's own name. Use it exactly as supplied in both languages.
- Keep sentences short. These are read on phones.

Tone: plain, warm, local. Write the way a careful neighbour would describe the place, not the way an agency would.`;

export class ClaudeSiteGenerator implements SiteGenerator {
  readonly key = "claude";

  private readonly client: Anthropic;
  private readonly fallback = new MockSiteGenerator();

  constructor(
    apiKey: string,
    private readonly model: string,
  ) {
    this.client = new Anthropic({ apiKey });
  }

  async generate(input: SiteGenerationInput): Promise<GeneratedSiteDraft> {
    const log = logger.child({ leadId: input.leadId, slug: input.slug });

    try {
      return await this.generateWithModel(input);
    } catch (error) {
      // A plain, factual page beats no page. The mock only rearranges the
      // business's own data, so falling back is always safe to publish.
      log.warn("generator.claude.fallback", {
        error: error instanceof Error ? error.message : String(error),
      });
      const draft = await this.fallback.generate(input);
      return {
        ...draft,
        unverifiedClaims: [...(draft.unverifiedClaims ?? []), "Generated by fallback — model unavailable"],
      };
    }
  }

  private async generateWithModel(input: SiteGenerationInput): Promise<GeneratedSiteDraft> {
    const { business } = input;
    const category = categoryLabel(business.primaryCategory);

    // Only facts. Anything absent is stated as absent so the model does not
    // treat a missing field as licence to invent one.
    const facts = {
      name: business.name,
      category: business.primaryCategory ?? "unknown",
      categoryLabel: { el: category.el, en: category.en },
      city: placeName(business.address?.city) ?? null,
      address: business.addressLocalized ?? null,
      phone: business.phone ?? null,
      email: business.email ?? null,
      hasFacebookPage: Boolean(business.facebook),
      openingHours: business.openingHours ?? null,
      photos: business.photos?.length ?? 0,
      reviews: business.reviews?.length ?? 0,
      note: "Fields that are null are genuinely unknown. Do not guess them. Use city.el in Greek copy and city.en in English copy.",
    };

    const response = await this.client.messages.parse({
      model: this.model,
      max_tokens: 16000,
      system: SYSTEM,
      messages: [
        {
          role: "user",
          content:
            `Write the copy for this business's website.\n\n` +
            `Available templates: ${TEMPLATES.map((t) => `${t.key} (${t.label}, suits ${t.suits.slice(0, 3).join("/")})`).join("; ")}\n\n` +
            `Business data:\n${JSON.stringify(facts, null, 2)}`,
        },
      ],
      output_config: {
        format: zodOutputFormat(draftSchema),
        // Copy for a one-page site is not a reasoning-heavy task.
        effort: "low",
      },
    });

    const parsed = response.parsed_output;
    if (!parsed) {
      throw new Error("Model returned no parseable output");
    }

    const template = pickTemplate(business.primaryCategory, input.slug);
    const chosen = TEMPLATES.find((entry) => entry.key === parsed.template) ?? template;

    return {
      template: chosen.key,
      model: this.model,
      unverifiedClaims: parsed.unverifiedClaims,
      usage: {
        inputTokens: response.usage.input_tokens,
        outputTokens: response.usage.output_tokens,
      },
      content: {
        defaultLocale: (input.defaultLocale ?? "el") as Locale,
        locales: input.locales ?? ["el", "en"],
        businessName: business.name,
        tagline: parsed.tagline,
        hero: {
          heading: parsed.heroHeading,
          subheading: parsed.heroSubheading,
        },
        statement: parsed.statement,
        about: parsed.about,
        services: parsed.services,
        hours: business.openingHours,
        contact: {
          phone: business.phone,
          email: business.email,
          address: business.addressLocalized,
          mapQuery: business.address?.formatted ?? business.name,
          location: business.location,
          facebook: business.facebook,
          instagram: business.instagram,
        },
        gallery: business.photos,
        theme: { template: chosen.key, accent: chosen.palette.accent },
      },
    };
  }
}
